/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idspack;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jpcap.JpcapCaptor;
import jpcap.NetworkInterface;
import jpcap.NetworkInterfaceAddress;

/**
 *
 * @author Ameya
 */
public class interinfo extends javax.swing.JFrame {
static NetworkInterface [] devices =JpcapCaptor.getDeviceList();
int xMouse;
int yMouse;
int num ;
public interinfo() {
                
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        txt4 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        minibtn = new javax.swing.JLabel();
        Closebtn = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        showbtn = new javax.swing.JLabel();
        intnum = new javax.swing.JTextField();
        intname = new javax.swing.JTextField();
        intdes = new javax.swing.JTextField();
        intadd = new javax.swing.JTextField();
        datal = new javax.swing.JTextField();
        datades = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        macad = new javax.swing.JTextArea();
        drag = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setText("Exit");
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 455, 50, -1));

        txt3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setText("Show");
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 455, 50, -1));

        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        getContentPane().add(minibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 10, -1, -1));

        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn.png"))); // NOI18N
        Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClosebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClosebtnMouseExited(evt);
            }
        });
        getContentPane().add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 10, -1, -1));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png"))); // NOI18N
        backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backbtnMouseExited(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 451, -1, -1));

        showbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png"))); // NOI18N
        showbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showbtnMouseExited(evt);
            }
        });
        getContentPane().add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 451, -1, -1));

        intnum.setEditable(false);
        intnum.setBackground(new java.awt.Color(255, 255, 255));
        intnum.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        intnum.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        intnum.setBorder(null);
        getContentPane().add(intnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 60, 230, 27));

        intname.setEditable(false);
        intname.setBackground(new java.awt.Color(255, 255, 255));
        intname.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        intname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        intname.setBorder(null);
        getContentPane().add(intname, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 115, 230, 27));

        intdes.setEditable(false);
        intdes.setBackground(new java.awt.Color(255, 255, 255));
        intdes.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        intdes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        intdes.setBorder(null);
        getContentPane().add(intdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 172, 230, 27));

        intadd.setEditable(false);
        intadd.setBackground(new java.awt.Color(255, 255, 255));
        intadd.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        intadd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        intadd.setBorder(null);
        getContentPane().add(intadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 226, 230, 27));

        datal.setEditable(false);
        datal.setBackground(new java.awt.Color(255, 255, 255));
        datal.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        datal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        datal.setBorder(null);
        getContentPane().add(datal, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 281, 230, 27));

        datades.setEditable(false);
        datades.setBackground(new java.awt.Color(255, 255, 255));
        datades.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        datades.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        datades.setBorder(null);
        getContentPane().add(datades, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 337, 230, 27));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        macad.setEditable(false);
        macad.setColumns(20);
        macad.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        macad.setRows(5);
        macad.setAutoscrolls(false);
        macad.setBorder(null);
        jScrollPane1.setViewportView(macad);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 396, 220, 27));

        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interface.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();

        this.setLocation(x- xMouse, y-yMouse);
    }//GEN-LAST:event_dragMouseDragged

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        this.setState(Splash.ICONIFIED);
    }//GEN-LAST:event_minibtnMouseClicked

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn_clk.png")));
        minibtn.setToolTipText("Click to Minimize");
    }//GEN-LAST:event_minibtnMouseEntered

    private void ClosebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseClicked
        setVisible(false);
    }//GEN-LAST:event_ClosebtnMouseClicked

    private void ClosebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseEntered
        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn_clk.png")));
        Closebtn.setToolTipText("Click to Close");
    }//GEN-LAST:event_ClosebtnMouseEntered

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        setVisible(false);
    }//GEN-LAST:event_backbtnMouseClicked

    private void backbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseEntered
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button_hower.png")));
        backbtn.setToolTipText("Click to go back");
    }//GEN-LAST:event_backbtnMouseEntered

    private void showbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showbtnMouseClicked
        
        num = Integer.parseInt(intnum.getText());
        intname.setText(devices[num].name);
        intdes.setText(devices[num].description);
        for (NetworkInterfaceAddress a : devices[num].addresses) {
                   intadd.setText(""+a.address);
            }
        datal.setText(devices[num].datalink_name);
        datades.setText(devices[num].datalink_description);
        for (byte b : devices[num].mac_address) {
                macad.append(""+Integer.toHexString(b & 0xff) + ":");
            }
        
    }//GEN-LAST:event_showbtnMouseClicked

    private void showbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showbtnMouseEntered
        showbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button_hower.png")));
        showbtn.setToolTipText("Click to Show");
    }//GEN-LAST:event_showbtnMouseEntered

    private void showbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showbtnMouseExited
        showbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png")));
    }//GEN-LAST:event_showbtnMouseExited

    private void backbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseExited
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png")));
    }//GEN-LAST:event_backbtnMouseExited

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn.png")));
    }//GEN-LAST:event_minibtnMouseExited

    private void ClosebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseExited
        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn.png")));
    }//GEN-LAST:event_ClosebtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interinfo().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closebtn;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField datades;
    private javax.swing.JTextField datal;
    private javax.swing.JLabel drag;
    private javax.swing.JTextField intadd;
    private javax.swing.JTextField intdes;
    private javax.swing.JTextField intname;
    public static javax.swing.JTextField intnum;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea macad;
    private javax.swing.JLabel minibtn;
    private javax.swing.JLabel showbtn;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    // End of variables declaration//GEN-END:variables
}
