/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idspack;

import DBLOGS.*;
import JImage.JIResizeImage;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
//import JImage.JIResizeImage;

import java.io.FileOutputStream;
import java.net.URL;
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author SOHAIL MOMIN
 */
public class logsinfo extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
//    int no;

    public logsinfo() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        delbtn = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        Closebtn = new javax.swing.JLabel();
        minibtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        endtime = new javax.swing.JLabel();
        lock = new javax.swing.JLabel();
        fcL = new javax.swing.JLabel();
        drag = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("Show");
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 456, 60, -1));

        txt6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        txt6.setForeground(new java.awt.Color(255, 255, 255));
        txt6.setText("Delete");
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 456, 60, -1));

        delbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png"))); // NOI18N
        delbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delbtnMouseExited(evt);
            }
        });
        getContentPane().add(delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 450, -1, -1));

        txt2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 22)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setText("Failure Count :");
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 180, -1));

        txt3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 22)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setText("Start Date & Time :");
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 190, -1));

        txt4.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 22)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setText("End Date & Time :");
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 180, -1));

        txt5.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 22)); // NOI18N
        txt5.setForeground(new java.awt.Color(255, 255, 255));
        txt5.setText("Unlock :");
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 180, -1));

        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 360, 220));

        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn.png"))); // NOI18N
        Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClosebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClosebtnMouseExited(evt);
            }
        });
        getContentPane().add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 8, 26, 19));

        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        getContentPane().add(minibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 8, 26, 19));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 450, 120, 40));
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 305, 190, 30));
        getContentPane().add(endtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 307, 190, 30));
        getContentPane().add(lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 388, 190, 30));
        getContentPane().add(fcL, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 389, 190, 30));

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logsinfo.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragMouseDragged

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void ClosebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseClicked
        setVisible(false);
        ShowLogsTable SLT=new ShowLogsTable();
        SLT.setVisible(true);
    }//GEN-LAST:event_ClosebtnMouseClicked

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        this.setState(Splash.ICONIFIED);
    }//GEN-LAST:event_minibtnMouseClicked


    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        System.out.println("column no " + ShowLogsTable.logidPK);
        // int a= ShowLogsTable.logidPK;
        Connection conn = null;
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Successfull...");

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select sdt, edt, unlock, fc from logs where logid=" + ShowLogsTable.logidPK + " ");
            while (rs.next()) {

                String sdt = rs.getString(1).toString();
                System.out.println("Start Time " + sdt);
                start.setText(sdt);

                String edt = rs.getString(2).toString();
                System.out.println("End Time " + edt);
                endtime.setText(edt);

                String unlock = rs.getString(3).toString();
                System.out.println("Unlock " + unlock);
                lock.setText(unlock);

                int fc = rs.getInt(4);
                System.out.println("Failure Count " + fc);
                String ab = Integer.toString(fc);
                fcL.setText(ab);

            }

            rs.close();

        } catch (Exception e) {
            e.printStackTrace();

        }
      

        try {
         PreparedStatement ps = conn.prepareStatement("select * from imgtable where logid=" + ShowLogsTable.logidPK + "");
         ResultSet rs = ps.executeQuery();
         System.out.println("Qury excuted");
         if (rs.next()) {//now on 1st row  

         Blob b = rs.getBlob(2);//2 means 2nd column data
         
         System.out.println("logid for image logid" + ShowLogsTable.logidPK);
         byte barr[] = b.getBytes(1, (int) b.length());//1 means first image  
                
         System.out.println(barr);
                   
         FileOutputStream fout = new FileOutputStream("src/images/Retrive/ " + ShowLogsTable.logidPK + "" + "I.jpg");
         //linearResizeBi(barr, 200, 200);
         
         fout.write(barr);

         fout.close();
         }//end of if  
         System.out.println("ok");

         conn.close();
         } catch (Exception e) {
         e.printStackTrace();
         }

         ImageIcon icon = new ImageIcon("src/images/Retrive/ " + ShowLogsTable.logidPK + "" + "I.jpg");
        
         jLabel.setIcon(icon);
         

    }//GEN-LAST:event_jLabel1MouseClicked

   


    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button_hower.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn_clk.png")));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn.png")));
    }//GEN-LAST:event_minibtnMouseExited

    private void ClosebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseEntered
        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn_clk.png")));
    }//GEN-LAST:event_ClosebtnMouseEntered

    private void ClosebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseExited
        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn.png")));
    }//GEN-LAST:event_ClosebtnMouseExited

    private void delbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delbtnMouseEntered
delbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button_hower.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_delbtnMouseEntered

    private void delbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delbtnMouseExited
delbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_delbtnMouseExited

    private void delbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delbtnMouseClicked
             setVisible(false);   
            
         deletelog w=new deletelog();
                 w.setVisible(true);
    }//GEN-LAST:event_delbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logsinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logsinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closebtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel delbtn;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel endtime;
    private javax.swing.JLabel fcL;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lock;
    private javax.swing.JLabel minibtn;
    private javax.swing.JLabel start;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    // End of variables declaration//GEN-END:variables

    private ImageIcon ImageIcon(URL resource) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
