/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idspack;
import DBLOGS.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import idspack.Startup;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.ImageIcon;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author SOHAIL MOMIN
 */
public class Mainfrm extends javax.swing.JFrame {

    int xMouse, yMouse;
    int timerun=0;
    /**
     * Creates new form Mainfrm
     */
    public Mainfrm() {
       
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
        
        txt4.setText("Welcome "+Startup.userName +" To IDS");
        new Thread()
        {
          public void run()
        {
           while(timerun==0)
        {
            Calendar cal=new GregorianCalendar();
             int second =cal.get(Calendar.SECOND);
        int min=cal.get(Calendar.MINUTE);
        int houre =cal.get(Calendar.HOUR);
        int AM_PM=cal.get(Calendar.AM_PM);
        
        String time=houre+":"+min+":"+second;
        jLabel2.setText(time);
      
         
        int month =cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day =cal.get(Calendar.DAY_OF_MONTH);
       jLabel1.setText(day+"/"+(month+1)+"/"+year);
        
        }
        }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drag = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        changepsw = new javax.swing.JLabel();
        minibtn = new javax.swing.JLabel();
        Closebtn = new javax.swing.JLabel();
        userbtn = new javax.swing.JLabel();
        logbtn = new javax.swing.JLabel();
        sniffbtn = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 20));

        jLabel1.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("20/20/2015");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 140, 30));

        jLabel2.setFont(new java.awt.Font("DS-Digital", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("4:21 PM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 140, 30));

        txt3.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 36)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setText("Admin");
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 110, -1));

        txt4.setFont(new java.awt.Font("Microsoft PhagsPa", 2, 30)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setText("Logs");
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 520, -1));

        txt5.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 36)); // NOI18N
        txt5.setForeground(new java.awt.Color(255, 255, 255));
        txt5.setText("Sniffer");
        getContentPane().add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 110, -1));

        txt6.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 36)); // NOI18N
        txt6.setForeground(new java.awt.Color(255, 255, 255));
        txt6.setText("Logs");
        getContentPane().add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 100, -1));

        changepsw.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        changepsw.setForeground(new java.awt.Color(255, 255, 255));
        changepsw.setText("About Us:");
        changepsw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changepsw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepswMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changepswMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changepswMouseExited(evt);
            }
        });
        getContentPane().add(changepsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 120, 30));

        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn.png"))); // NOI18N
        minibtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minibtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtnMouseExited(evt);
            }
        });
        getContentPane().add(minibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 26, 19));

        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn.png"))); // NOI18N
        Closebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClosebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClosebtnMouseExited(evt);
            }
        });
        getContentPane().add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 26, 19));

        userbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/userbtn.png"))); // NOI18N
        userbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userbtnMouseExited(evt);
            }
        });
        getContentPane().add(userbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/logbtn.png"))); // NOI18N
        logbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logbtnMouseExited(evt);
            }
        });
        getContentPane().add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        sniffbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/sniffbtn.png"))); // NOI18N
        sniffbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sniffbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sniffbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sniffbtnMouseExited(evt);
            }
        });
        getContentPane().add(sniffbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainbg.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        setSize(new java.awt.Dimension(700, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragMouseDragged

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragMousePressed

    private void minibtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseClicked
        this.setState(Splash.ICONIFIED);
    }//GEN-LAST:event_minibtnMouseClicked

    private void minibtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseEntered
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn_clk.png")));
    }//GEN-LAST:event_minibtnMouseEntered

    private void minibtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtnMouseExited
        minibtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/mini_btn.png")));
    }//GEN-LAST:event_minibtnMouseExited

    private void ClosebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ClosebtnMouseClicked

    private void ClosebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseEntered
        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn_clk.png")));
    }//GEN-LAST:event_ClosebtnMouseEntered

    private void ClosebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosebtnMouseExited
        Closebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/close_btn.png")));
    }//GEN-LAST:event_ClosebtnMouseExited

    private void sniffbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sniffbtnMouseClicked
        Sniffer sn = new Sniffer();
       this.setVisible(false);
        sn.setVisible(true);
    }//GEN-LAST:event_sniffbtnMouseClicked

    private void sniffbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sniffbtnMouseEntered
       voicesniffer();
        sniffbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/sniffbtn_hower.png")));
    }//GEN-LAST:event_sniffbtnMouseEntered

    private void sniffbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sniffbtnMouseExited
        sniffbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/sniffbtn.png")));
    }//GEN-LAST:event_sniffbtnMouseExited

    private void logbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbtnMouseClicked
        ShowLogsTable sl = new ShowLogsTable();
        this.setVisible(false);
        sl.setVisible(true);
    }//GEN-LAST:event_logbtnMouseClicked

    private void logbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbtnMouseEntered
        voicelog();       
        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/logbtn_hower.png")));
        
    }//GEN-LAST:event_logbtnMouseEntered

    private void logbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbtnMouseExited
        logbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/logbtn.png")));
    }//GEN-LAST:event_logbtnMouseExited

    private void userbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseClicked
            ChangePsw cp = new ChangePsw();
            this.setVisible(false);
            cp.setVisible(true);
    }//GEN-LAST:event_userbtnMouseClicked

    private void userbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseEntered
        voiceadmin();
        userbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/userbtn_hower.png")));
    }//GEN-LAST:event_userbtnMouseEntered

    private void userbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userbtnMouseExited
        userbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/userbtn.png")));
    }//GEN-LAST:event_userbtnMouseExited

    private void changepswMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepswMouseEntered
        Font font = new Font ("Microsoft pagspa", Font.BOLD, 20);
        changepsw.setFont (font);
        changepsw.setForeground(Color.white);
    }//GEN-LAST:event_changepswMouseEntered

    private void changepswMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepswMouseExited
        Font font = new Font ("Microsoft PhagsPa", NORMAL, 14);
        changepsw.setFont (font);
        changepsw.setForeground(Color.white);
    }//GEN-LAST:event_changepswMouseExited

    private void changepswMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepswMouseClicked
      about sl = new about();
        this.setVisible(false);
        sl.setVisible(true);
        setVisible(false);
       
    }//GEN-LAST:event_changepswMouseClicked

    
    void voicelog()
      {
         InputStream in;
         try{
             in=new FileInputStream(new File ("src/Voice/log.wav"));
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
             
         }
         catch(Exception e){
            // jOptionPane1.showMessageDialog(null, e);
         }
      }
    
     
    void voicesniffer()
      {
         InputStream in;
         try{
             in=new FileInputStream(new File ("src/Voice/sniffer.wav"));
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
             
         }
         catch(Exception e){
            // jOptionPane1.showMessageDialog(null, e);
         }
      }
     
    void voiceadmin()
      {
         InputStream in;
         try{
             in=new FileInputStream(new File ("src/Voice/admin.wav"));
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
             
         }
         catch(Exception e){
            // jOptionPane1.showMessageDialog(null, e);
         }
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Closebtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel changepsw;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logbtn;
    private javax.swing.JLabel minibtn;
    private javax.swing.JLabel sniffbtn;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel userbtn;
    // End of variables declaration//GEN-END:variables
}
