/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idspack;
import JImage.JIResizeImage;
import static idspack.Splash.SOCKET_PORT;
import static idspack.Splash.file_to_send;
import static idspack.Splash.id;
import static idspack.Splash.userName;
import sun.audio.*;
import java.io.*;
import java.awt.Color;
import java.sql.*;
import java.util.TimeZone;
import java.util.Date;
import java.text.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.media.Buffer;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.font.*;
import java.awt.geom.AffineTransform;
import java.io.BufferedInputStream;
import java.io.OutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import javax.swing.JOptionPane;

/**
 *
 * @author SOHAIL MOMIN
 */
public class Startup extends javax.swing.JFrame {

    public final static int SOCKET_PORT = 50000;  // you may change this
    public static String file_to_send ;  // you may change this
    int flags = 0;
    int count = 0;
    int fc = 3;
    public static int id;
    String unlock;
    DataOutputStream os;
   static String shut;
    
    int xMouse;
    int yMouse;
    static String userName;
    static String psw;
    public static int flag;
DataInputStream is;
    Player player;
    BufferedImage bi;
    String fn;
    int no;

        
    /**
     * Creates new form Startup
     */
    public Startup() {
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        changepsw = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txt = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        pswd = new javax.swing.JPasswordField();
        clearlbl1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        submitlbl = new javax.swing.JLabel();
        clearlbl = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        tbWebCam = new javax.swing.JToggleButton();
        tbCapture = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changepsw.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 16)); // NOI18N
        changepsw.setForeground(new java.awt.Color(255, 255, 255));
        changepsw.setText("Forgot Your Password");
        changepsw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changepsw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepswMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changepswMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changepswMouseExited(evt);
            }
        });
        getContentPane().add(changepsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 260, 30));

        txt1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("Log into IDS");
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 525, 100, -1));

        txt.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setText("Log into OS");
        getContentPane().add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 528, 100, 20));

        uname.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        uname.setBorder(null);
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 348, 230, 30));

        pswd.setBorder(null);
        getContentPane().add(pswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 414, 230, 30));

        clearlbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png"))); // NOI18N
        clearlbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearlbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearlbl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearlbl1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearlbl1MouseExited(evt);
            }
        });
        getContentPane().add(clearlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 520, -1, 40));

        txt2.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 18)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setText("Clear");
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 528, 50, 20));

        submitlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png"))); // NOI18N
        submitlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitlblMouseExited(evt);
            }
        });
        getContentPane().add(submitlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 125, 40));

        clearlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png"))); // NOI18N
        clearlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearlblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearlblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearlblMouseExited(evt);
            }
        });
        getContentPane().add(clearlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 520, 125, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splash 768.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbWebCam.setBackground(new java.awt.Color(255, 255, 255));
        tbWebCam.setForeground(new java.awt.Color(102, 153, 255));
        tbWebCam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        getContentPane().add(tbWebCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 290));

        tbCapture.setBackground(new java.awt.Color(255, 255, 255));
        tbCapture.setForeground(new java.awt.Color(102, 153, 255));
        tbCapture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        tbCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCaptureActionPerformed(evt);
            }
        });
        getContentPane().add(tbCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void changepswMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepswMouseClicked
        System.out.println("UserName "+userName);
        System.out.println("UserName "+psw);
        
        ServerSocket ssock = null;
        Socket sock = null;
        
        try {
            ssock = new ServerSocket(SOCKET_PORT);
        } catch (IOException ex) {
            Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            sock = ssock.accept();
        } catch (IOException ex) {
            Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            os = new DataOutputStream(sock.getOutputStream());
        } catch (IOException ex) {
            Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            os.writeUTF(userName);
        } catch (IOException ex) {
            Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            os.writeUTF(psw);
        } catch (IOException ex) {
            Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            os.flush();
        } catch (IOException ex) {
            Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_changepswMouseClicked

    private void changepswMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepswMouseEntered
        Font font = new Font ("Microsoft pagspa", Font.BOLD, 20);
        changepsw.setFont (font);
        changepsw.setForeground(Color.white);
    }//GEN-LAST:event_changepswMouseEntered

    private void changepswMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepswMouseExited
        Font font = new Font ("Microsoft PhagsPa", NORMAL, 14);
        changepsw.setFont (font);
        changepsw.setForeground(Color.white);
    }//GEN-LAST:event_changepswMouseExited

    private void submitlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitlblMouseClicked
    
          clearlbl1.setVisible(false);  
          txt.setVisible(false);  
        String usr = uname.getText();
        String psd = new String(pswd.getPassword());
        if (usr.equals(userName) && psd.equals(psw)) {
            if (count == 0 || count == 1 || count==2) {
                jOptionPane1.showMessageDialog(null, "Login Successfully..!","Success",JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                voicemain();
                new Mainfrm().setVisible(true);
            } else {
                unlock = "Successful";
                // logsid();
                endlogs();
                fclogs();
                unlocklogs();

                jOptionPane1.showMessageDialog(null, "Login Successfully..!","Success",JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                voicemain();
                new Mainfrm().setVisible(true);
            }
        } else {
            jOptionPane1.showMessageDialog(null, "Please Enter correct Username & Password","Error",JOptionPane.ERROR_MESSAGE);
            count++;

            pswd.setText(null);
            uname.setText(null);
            if (count == 3) {
                logs();
                try {
                    initCamera();
                } catch (IOException ex) {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoPlayerException ex) {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (CannotRealizeException ex) {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                for (int i = 0; i < 40000; i++) {
                    System.out.println(i);
                }

                captureimg();
                saveimg();
                imgstore();

                try {
                    // player.close();
                    stopCamera();
                } catch (IOException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoPlayerException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                } catch (CannotRealizeException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("End of Camera ");
                //logsid();
                voice();
                 try {
                    sendimg();
                } catch (IOException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                 for(int i=0;i<20000000;i++)
                     for(int j=0; j<1275;j++);
                 
                try {
                    shutdown();         
                } catch (IOException ex) {
                    Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (count > 3) {
                fc++;

            }
            
        }

    }//GEN-LAST:event_submitlblMouseClicked

    public void shutdown() throws IOException
    {
        Thread t = new Thread(new Runnable(){
            
    
            @Override
            public void run() {
                Socket sock=null;
                String server = "192.168.0.100";
                try {
                    sock = new Socket(server,  SOCKET_PORT);
                } catch (IOException ex) {
                    Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                try {
                    is = new DataInputStream(sock.getInputStream());
                } catch (IOException ex) {
                    Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
                }
   
    
                try {
                    shut = is.readUTF();
                } catch (IOException ex) {
                    Logger.getLogger(Startup.class.getName()).log(Level.SEVERE, null, ex);
                }
    System.out.println("for in fucntion Shutdown "+shut);
    
      if("5".equals(shut))
                    {
                      Runtime runtime= Runtime.getRuntime();
                    try{
                      Process proc=runtime.exec("shutdown -s -t 0");
                      }catch (Exception ex){
            
                      jOptionPane1.showMessageDialog(null, ex.getMessage());
                        }
          
                    }

            }
    });
        t.start();
    }
    
    
    private void captureimg() {
        FrameGrabbingControl fgc = (FrameGrabbingControl) player.getControl("javax.media.control.FrameGrabbingControl");
        Buffer buffer = fgc.grabFrame();

        BufferToImage bti = new BufferToImage((VideoFormat) buffer.getFormat());
        Image image = bti.createImage(buffer);

        JIResizeImage resize = new JIResizeImage();
        bi = (BufferedImage) image;
        System.out.println("binary file"+bi);
        Image imageresize = resize.rescale(bi, 370, 210);

        this.setImageButton(this.tbCapture, imageresize);

    }

    private void saveimg() {
        fn = "src/images/Insert/ " + id + "" + "I.jpg";
        try {
            File make = new File(fn);
            try {
                 bi = linearResizeBi(bi, 360, 220);
                ImageIO.write(bi, "jpg", make);
            } catch (Exception ex) {
                Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {

        }

    }
    
    public void sendimg() throws IOException
    {
        boolean ecit=true;
        file_to_send = fn ;
        FileInputStream fis = null;
        BufferedInputStream bis = null;
        OutputStream os = null;
        ServerSocket servsock = null;
        Socket sock = null;
        try 
        {
            servsock = new ServerSocket(SOCKET_PORT);
            try {
                
            servsock.setSoTimeout(10000);
            sock = servsock.accept();
            
            System.out.println("Accepted connection : " + sock);
         
            File myFile = new File (file_to_send);
            byte [] mybytearray  = new byte [(int)myFile.length()];
            fis = new FileInputStream(myFile);
            bis = new BufferedInputStream(fis);
            bis.read(mybytearray,0,mybytearray.length);
            os = sock.getOutputStream();
            System.out.println("Sending " + file_to_send + "(" + mybytearray.length + " bytes)");
            os.write(mybytearray,0,mybytearray.length);
            os.flush();
            System.out.println("Done.");
            flags = 1;
            
            }
        finally
        {
            if (bis != null){ bis.close();}            
            if (os != null) {os.close();}
            if (sock!=null) {sock.close();}
        }
            
            
        }
                
        
        finally
        {
            if (servsock != null) servsock.close();
        }
        
        return;
}
    
static public BufferedImage linearResizeBi(BufferedImage origin, int width, int height) {
        BufferedImage resizedImage = new BufferedImage(width, height ,BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizedImage.createGraphics();
        float xScale = (float)width / origin.getWidth();
        float yScale = (float)height / origin.getHeight();
        AffineTransform at = AffineTransform.getScaleInstance(xScale,yScale);
        g.drawRenderedImage(origin,at);
        g.dispose();
        return resizedImage;
    }
    void imgstore() {
        Connection conn = null; 
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Successfull...");

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
        //no = Splash.id;
        try {
            PreparedStatement ps = conn.prepareStatement("insert into imgtable values(?,?)");
            ps.setInt(1, id);

            FileInputStream fin = new FileInputStream("src/images/Insert/ " + id + "" + "I.jpg");

            ps.setBinaryStream(2, fin, fin.available());
            int i = ps.executeUpdate();
            System.out.println(i + " records affected");

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        //Splash.flag = 1;
        //this.dispose();
    }

    public void logs() {

        // public static void write(String f, String s) throws IOException {
        TimeZone tz = TimeZone.getTimeZone("EST"); // or PST, MID, etc ...
        Date now = new Date();
        DateFormat df = new SimpleDateFormat("dd.mm.yyyy   hh:mm:ss ");
        df.setTimeZone(tz);
        String currentTime = df.format(now);

        System.out.println(currentTime);

        Connection conn1 = null;
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn1 = DriverManager.getConnection(url, username, password);

            try {
                Statement stmt;
                stmt = conn1.createStatement();

            //    String sql = "Update logs set sdt = ('" + currentTime + "') " + " where logid =('" + id + "')";

                String sql = "INSERT INTO logs(sdt) "
                    + "VALUES('" + currentTime + "')";
            
                stmt.executeUpdate(sql);

                System.out.println("start time & Date inserted");
                
                //logsid();
                conn1.close();
                //aWriter.write(currentTime + " " + s + "\n");
            } catch (Exception e) {
                e.printStackTrace();

            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }
          Connection conn = null;
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn = DriverManager.getConnection(url, username, password);
            System.out.println("Connection Successfull...");

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

        
        
         try {
               
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from logs where sdt = ('" + currentTime + "') ");
            while (rs.next()) {
                int no = rs.getInt(1);
                System.out.println("logsid no befor" + no);
                id = no;
            }
        } catch (Exception e) {
            e.printStackTrace();

        }

    }

    public void endlogs() {

       
        TimeZone tz = TimeZone.getTimeZone("EST"); // or PST, MID, etc ...
        Date now = new Date();
        DateFormat df = new SimpleDateFormat("dd.mm.yyyy   hh:mm:ss ");
        df.setTimeZone(tz);
        String currentTime = df.format(now);

        System.out.println(currentTime);

        Connection conn1 = null;
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn1 = DriverManager.getConnection(url, username, password);

            try {
                Statement stmt;
                stmt = conn1.createStatement();

                String sql = "Update logs set edt = ('" + currentTime + "') " + " where logid =('" + id + "')";
                stmt.executeUpdate(sql);

                System.out.println("End Date $ Time inserted");
                conn1.close();
               
            } catch (Exception e) {
                e.printStackTrace();

            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

    }

    public void fclogs() {

        Connection conn1 = null;
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn1 = DriverManager.getConnection(url, username, password);

            try {
                Statement stmt;
                stmt = conn1.createStatement();

                String sql = "Update logs set fc = ('" + fc + "') " + " where logid =('" + id + "')";
                stmt.executeUpdate(sql);

                System.out.println("Failure count inserted");
                conn1.close();
                
            } catch (Exception e) {
                e.printStackTrace();

            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

    }

    public void unlocklogs() {

        Connection conn1 = null;
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn1 = DriverManager.getConnection(url, username, password);

            try {
                Statement stmt;
                stmt = conn1.createStatement();

                String sql = "Update logs set unlock = ('" + unlock + "') " + " where logid =('" + id + "')";

                stmt.executeUpdate(sql);

                System.out.println("Unlock inserted");
                conn1.close();
             
            } catch (Exception e) {
                e.printStackTrace();

            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

    }
    
         
      void voice()
      {
         InputStream in;
         try{
             in=new FileInputStream(new File ("src/Voice/Sleep Away.wav"));
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
             
         }
         catch(Exception e){
             jOptionPane1.showMessageDialog(null, e);
         }
         
         
      }
      void voiceOS()
      {
         InputStream in;
         try{
             in=new FileInputStream(new File ("src/Voice/on.wav"));
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
             
         }
         catch(Exception e){
             jOptionPane1.showMessageDialog(null, e);
         }
         
         
      }
      
      void voicemain()
      {
         InputStream in;
         try{
             in=new FileInputStream(new File ("src/Voice/main.wav"));
             AudioStream audios=new AudioStream(in);
             AudioPlayer.player.start(audios);
             
         }
         catch(Exception e){
             jOptionPane1.showMessageDialog(null, e);
         }
         
         
      }
     private void initCamera() throws IOException, NoPlayerException, CannotRealizeException {
        MediaLocator ml = new MediaLocator("vfw://0");
        player = Manager.createRealizedPlayer(ml);
        this.tbWebCam.add(player.getVisualComponent());
        player.start();
        
         tbCapture.setVisible(false);
                tbWebCam.setVisible(false);
    }

    private void setImageButton(JToggleButton tbutton, Image image) {
        tbutton.setIcon(new ImageIcon(image));
    }
    
     private void stopCamera() throws IOException, NoPlayerException, CannotRealizeException {
        
        player.close();
    }
    
    private void submitlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitlblMouseEntered
        submitlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button_hower.png")));
    }//GEN-LAST:event_submitlblMouseEntered

    private void submitlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitlblMouseExited
        submitlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png")));
    }//GEN-LAST:event_submitlblMouseExited

    private void clearlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearlblMouseClicked
        uname.setText(null);
        pswd.setText(null);
        
    }//GEN-LAST:event_clearlblMouseClicked

    private void clearlblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearlblMouseEntered
        clearlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button_hower.png")));
    }//GEN-LAST:event_clearlblMouseEntered
    
    private void clearlblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearlblMouseExited
        clearlbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button/button.png")));
    }//GEN-LAST:event_clearlblMouseExited

    private void tbCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCaptureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCaptureActionPerformed

    private void clearlbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearlbl1MouseClicked
    submitlbl.setVisible(false);
    txt1.setVisible(false);
        String usr = uname.getText();
        String psd = new String(pswd.getPassword());
        if (usr.equals(userName) && psd.equals(psw)) {
            if (count == 0 || count == 1 || count==2) {
                jOptionPane1.showMessageDialog(null, "Login Successfully..!","Success",JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                voiceOS();
                System.exit(0);
            } else {
                unlock = "Successful";
                // logsid();
                endlogs();
                fclogs();
                unlocklogs();

                jOptionPane1.showMessageDialog(null, "Login Successfully..!","Success",JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                new Mainfrm().setVisible(true);
            }
        } else {
            jOptionPane1.showMessageDialog(null, "Please Enter correct Username & Password","Error",JOptionPane.ERROR_MESSAGE);
            count++;

            pswd.setText(null);
            uname.setText(null);
            if (count == 3) {
                logs();
                try {
                    initCamera();
                } catch (IOException ex) {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoPlayerException ex) {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (CannotRealizeException ex) {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                }

                for (int i = 0; i < 40000; i++) {
                    System.out.println(i);
                }

                captureimg();
                saveimg();
                 try {
                    sendimg();
                } catch (IOException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                }
                imgstore();

                try {
                    // player.close();
                    stopCamera();
                } catch (IOException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoPlayerException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                } catch (CannotRealizeException ex) {
                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("End of Camera ");
                //logsid();

            } else if (count > 3) {
                fc++;

            }
        }

    }//GEN-LAST:event_clearlbl1MouseClicked

    private void clearlbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearlbl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearlbl1MouseEntered

    private void clearlbl1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearlbl1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearlbl1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        Connection conn = null;
        try {
            String driverName = "oracle.jdbc.driver.OracleDriver";
            Class.forName(driverName);
            String serverName = "SOHAIL-PC";
            String serverPort = "1521";
            String sid = "XE";
            String url = "jdbc:oracle:thin:@" + serverName + ":" + serverPort + ":" + sid;
            String username = "ids";
            String password = "mypassword";
            conn = DriverManager.getConnection(url, username, password);
            // System.out.println("Connection Successfull...");

            try {

                Statement st = conn.createStatement();

                ResultSet rs = st.executeQuery("Select * from login");
                while (rs.next()) {

                    userName = rs.getString(1).toString();
                    psw = rs.getString(2).toString();
                    // System.out.println(" " + userName +" " + psw);
                }
                rs.close();
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();

            }

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e);
        }

        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Thread.sleep(1500);
                } catch (Exception e) {

                }
                new Startup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel changepsw;
    private javax.swing.JLabel clearlbl;
    private javax.swing.JLabel clearlbl1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JLabel submitlbl;
    private javax.swing.JToggleButton tbCapture;
    private javax.swing.JToggleButton tbWebCam;
    private javax.swing.JLabel txt;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
