/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package idspack;
import java.sql.*;
import JImage.JIResizeImage;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.FileDialog;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.media.NoPlayerException;
import javax.media.CannotRealizeException;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.media.Manager;
import javax.media.control.FrameGrabbingControl;
import javax.media.Buffer;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import JImage.JIResizeImage;
//import java.io.FileInputStream;
import java.io.*; 
/**
 *
 * @author Hp
 */
public class WebCamForm extends javax.swing.JFrame {
    
    Player player;
    BufferedImage bi;
    String fn;
    int no;
    
    /**
     * Creates new form WebCamForm
     */
    public WebCamForm() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("icon.png")).getImage());
        
        try 
        {
            initCamera();
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (NoPlayerException ex) 
        {
            Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (CannotRealizeException ex) 
        {
            Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    private void initCamera() throws IOException, NoPlayerException, CannotRealizeException {  
        MediaLocator ml = new MediaLocator("vfw://0");
        player = Manager.createRealizedPlayer(ml);
        this.tbWebCam.add(player.getVisualComponent());
        player.start(); 
        } 
    private void setImageButton(JToggleButton tbutton, Image image) { 
        tbutton.setIcon(new ImageIcon(image));
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbWebCam = new javax.swing.JToggleButton();
        tbCapture = new javax.swing.JToggleButton();
        bCapture = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        lTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WebCam");

        tbWebCam.setBackground(new java.awt.Color(255, 255, 255));
        tbWebCam.setForeground(new java.awt.Color(102, 153, 255));
        tbWebCam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        tbCapture.setBackground(new java.awt.Color(255, 255, 255));
        tbCapture.setForeground(new java.awt.Color(102, 153, 255));
        tbCapture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        tbCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCaptureActionPerformed(evt);
            }
        });

        bCapture.setBackground(new java.awt.Color(255, 255, 255));
        bCapture.setForeground(new java.awt.Color(102, 153, 255));
        bCapture.setText("Capture");
        bCapture.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        bCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCaptureActionPerformed(evt);
            }
        });

        bSave.setBackground(new java.awt.Color(255, 255, 255));
        bSave.setForeground(new java.awt.Color(102, 153, 255));
        bSave.setText("Save");
        bSave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        lTitle.setBackground(new java.awt.Color(255, 255, 255));
        lTitle.setFont(new java.awt.Font("Illuminate", 0, 12)); // NOI18N
        lTitle.setForeground(new java.awt.Color(102, 153, 255));
        lTitle.setText("WEBCAM APPLICATION & CAPTURE IMAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(bCapture, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbWebCam, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbCapture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(lTitle)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbWebCam, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(tbCapture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSave)
                    .addComponent(bCapture))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCaptureActionPerformed
        // TODO add your handling code here:
        FrameGrabbingControl fgc = (FrameGrabbingControl) player.getControl("javax.media.control.FrameGrabbingControl");
        Buffer buffer = fgc.grabFrame();
        
        BufferToImage bti = new BufferToImage((VideoFormat) buffer.getFormat());
        Image image = bti.createImage(buffer);
        
        JIResizeImage resize = new JIResizeImage();
        bi = (BufferedImage) image;
        System.out.println(bi);
        Image imageresize = resize.rescale(bi, 210,220);
         
        this.setImageButton(this.tbCapture, imageresize);
    }//GEN-LAST:event_bCaptureActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        // TODO add your handling code here:
           FileDialog fd = new FileDialog(WebCamForm.this, "Save Image", FileDialog.SAVE);
        fd.show();
        
        if (fd.getFile() != null) 
        {
            fn = fd.getDirectory() + fd.getFile() + ".jpg";
            try
            {
                File make = new File(fn);
                try
                {
                    ImageIO.write(bi, "jpg", make);
                }
                catch (IOException ex)
                {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            catch (Exception ex)
            {
                
            }
        }
    }//GEN-LAST:event_bSaveActionPerformed

    private void tbCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCaptureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCaptureActionPerformed

    
  private void captureimg()
   {
       FrameGrabbingControl fgc = (FrameGrabbingControl) player.getControl("javax.media.control.FrameGrabbingControl");
        Buffer buffer = fgc.grabFrame();
        
        BufferToImage bti = new BufferToImage((VideoFormat) buffer.getFormat());
       Image image = bti.createImage(buffer);
         
        JIResizeImage resize = new JIResizeImage();
       bi = (BufferedImage) image;
       System.out.println(bi);
        Image imageresize = resize.rescale(bi, 210,220);
        
       this.setImageButton(this.tbCapture, imageresize);
   }
   
   
  private void saveimg()
   {
        fn="K:\\6th sem\\Project\\Project IDS Moduls\\WebCam\\photos\\Insert\\ "+"g.jpg";
            try
            {
                File make = new File(fn);
                try
                {
                    ImageIO.write(bi, "jpg", make);
                }
                catch (Exception ex)
                {
                    Logger.getLogger(WebCamForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            catch (Exception ex)
            {
            
            }
       
   }
   
   void imgstore()
   {
        Connection conn=null;
         try
      {
          String driverName ="oracle.jdbc.driver.OracleDriver";
          Class.forName(driverName);
         String serverName="SOHAIL-PC";
           String serverPort="1521";
           String sid="XE";
           String url="jdbc:oracle:thin:@"+ serverName + ":" + serverPort + ":" + sid;
           String username="ids";
           String password="mypassword";
           conn=DriverManager.getConnection(url,username,password);
           System.out.println("Connection Successfull...");
           
       }
       catch(ClassNotFoundException | SQLException e)
       {
           System.out.println(e);
       }
         
          
         
         no=Splash.id;
         
         
         
         
         
     try
     {
           PreparedStatement ps=conn.prepareStatement("insert into imgtable values(?,?)");  
           ps.setString(1,"sonoo");  
  
         FileInputStream fin=new FileInputStream("K:\\6th sem\\Project\\Project IDS Moduls\\WebCam\\photos\\Insert\\ "+"g.jpg");  
          
         ps.setBinaryStream(2,fin,fin.available());  
              int i=ps.executeUpdate();  
                  System.out.println(i+" records affected");  
          
                      conn.close();  
             }catch (Exception e) {
                    e.printStackTrace();}  
            
   Splash.flag=1;
   this.dispose();
   
   }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        WebCamForm form = new WebCamForm();
        form.setVisible(true);
       
       for(int i=0;i<40000;i++) 
       {
       System.out.println(i);
       }
        
         form.captureimg();
         
       form.saveimg();
       
       form.imgstore();
       
       //form.setVisible(false);
       form.setEnabled(false);
      //System.exit(0);
       form.dispose();
       //Splash addPage=new Splash();
         //        addPage.setVisible(true);
         
      
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebCamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebCamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebCamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebCamForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

     //  System.exit(0);
        
        
        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebCamForm().setVisible(true);
            }
        });*/
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCapture;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lTitle;
    private javax.swing.JToggleButton tbCapture;
    private javax.swing.JToggleButton tbWebCam;
    // End of variables declaration//GEN-END:variables
}
